import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * OpenClaw Next - Memory Explorer Component
 * Visualizes L1 (Context), L2 (Knowledge), and L3 (Soul) layers
 */
import { useState } from 'react';
export const MemoryExplorer = ({ layers }) => {
    const [activeLayer, setActiveLayer] = useState('active');
    return (_jsxs("div", { className: "card h-full flex flex-col", children: [_jsxs("div", { className: "p-4 border-b border-[var(--color-border)]", children: [_jsx("h3", { className: "font-bold mb-4 flex items-center gap-2", children: "\uD83E\uDDE0 Persistent Hierarchical Memory" }), _jsx("div", { className: "flex gap-1 bg-[var(--color-bg)] p-1 rounded-lg", children: ['active', 'knowledge', 'soul'].map((l) => (_jsxs("button", { onClick: () => setActiveLayer(l), className: `flex-1 py-1.5 px-3 rounded-md text-xs font-medium transition-all ${activeLayer === l
                                ? 'bg-[var(--color-surface)] shadow-sm text-[var(--color-primary)]'
                                : 'text-[var(--color-text-muted)] hover:text-[var(--color-text)]'}`, children: [l === 'active' && 'L1: Active', l === 'knowledge' && 'L2: Knowledge', l === 'soul' && 'L3: Soul'] }, l))) })] }), _jsxs("div", { className: "flex-1 overflow-auto p-4", children: [activeLayer === 'active' && (_jsx("div", { className: "space-y-3", children: layers.l1.map((msg, i) => (_jsxs("div", { className: `p-3 rounded-lg border ${msg.role === 'user' ? 'bg-[var(--color-primary)]/5 border-[var(--color-primary)]/20' : 'bg-[var(--color-surface-hover)] border-[var(--color-border)]'}`, children: [_jsxs("div", { className: "flex justify-between items-center mb-1", children: [_jsx("span", { className: "text-[10px] uppercase font-bold tracking-wider opacity-50", children: msg.role }), _jsxs("span", { className: "text-[10px] opacity-50", children: [msg.tokens, " tokens"] })] }), _jsx("p", { className: "text-sm", children: msg.content })] }, i))) })), activeLayer === 'knowledge' && (_jsx("div", { className: "space-y-3", children: layers.l2.map((entry, i) => (_jsxs("div", { className: "p-3 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)]", children: [_jsxs("div", { className: "flex justify-between items-center mb-2", children: [_jsx("span", { className: "badge-info text-[10px]", children: entry.category }), _jsx("span", { className: "text-[10px] opacity-50", children: new Date(entry.timestamp).toLocaleDateString() })] }), _jsx("p", { className: "text-sm font-medium mb-1", children: entry.content }), _jsx("div", { className: "flex gap-1", children: entry.tags?.map((t) => (_jsx("span", { className: "text-[9px] px-1 bg-[var(--color-bg)] rounded border border-[var(--color-border)]", children: t }, t))) })] }, i))) })), activeLayer === 'soul' && (_jsx("div", { className: "space-y-2", children: layers.l3.map((directive, i) => (_jsxs("div", { className: "flex gap-3 items-start p-2 hover:bg-[var(--color-surface-hover)] rounded-md transition-colors", children: [_jsx("span", { className: "text-[var(--color-primary)] text-xs mt-0.5", children: "\u2022" }), _jsxs("p", { className: "text-sm text-[var(--color-text-muted)] leading-relaxed italic", children: ["\"", directive.content, "\""] })] }, i))) }))] })] }));
};
